// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Helper to add SSL parameters to the database URL
const getDatabaseUrl = () => {
  const baseUrl = env("DATABASE_URL");
  // Add SSL parameters if not already present
  if (baseUrl && !baseUrl.includes('sslmode')) {
    const separator = baseUrl.includes('?') ? '&' : '?';
    return `${baseUrl}${separator}sslmode=require`;
  }
  return baseUrl;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx src/lib/prisma.ts`,
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
